service: update-task
frameworkVersion: ">=1.30.0"
plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements
custom:
  accountid: ${env:AWS_ACCOUNT_ID}
  cloud: ${env:TARGET_CLOUD}
  region: ${env:TARGET_REGION}
  logDataBucket: ${env:TASK_EXEC_LOG_DATA_BUCKET}
  resultDataBucket: ${env:TASK_EXEC_RESULT_DATA_BUCKET}
  updateTaskQueue: ${env:TASK_EXEC_UPDATE_TASK_QUEUE}
  uploadTaskIssuesQueue: ${env:TASK_EXEC_UPLOAD_TASK_ISSUES_QUEUE}
  dotenv:
    path: ../.env
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  region: ${env:TARGET_REGION}
  runtime: python3.8
  stage: dev
  lambdaHashingVersion: 20201221 # optional, version of hashing algorithm that should be used by the framework
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:${self:custom.cloud}:s3:::${self:custom.logDataBucket}/*"
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:${self:custom.cloud}:s3:::${self:custom.resultDataBucket}/*"
    - Effect: Allow
      Action:
        - sqs:ListQueues
      Resource: "arn:${self:custom.cloud}:sqs:${self:provider.region}:*:*"
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueUrl
      Resource: "arn:${self:custom.cloud}:sqs:*:*:${self:custom.updateTaskQueue}"
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:DeleteMessage
        - sqs:GetQueueUrl
      Resource: "arn:${self:custom.cloud}:sqs:*:*:${self:custom.uploadTaskIssuesQueue}"
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:${self:custom.cloud}:dynamodb:${self:custom.region}:${self:custom.accountid}:*"

functions:
  update_task:
    handler: update_task.update_task
    role: arn:${self:custom.cloud}:iam::${self:custom.accountid}:role/task-execution-pipeline
    tracing: true
    environment:
      ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
      CLOUD: ${env:TARGET_CLOUD}
      REGION: ${env:TARGET_REGION}
      LOG_DATA_BUCKET: ${env:TASK_EXEC_LOG_DATA_BUCKET}
      RESULT_DATA_BUCKET: ${env:TASK_EXEC_RESULT_DATA_BUCKET}
      UPDATE_TASK_QUEUE: ${env:TASK_EXEC_UPDATE_TASK_QUEUE}
      UPLOAD_TASK_ISSUES_QUEUE: ${env:TASK_EXEC_UPLOAD_TASK_ISSUES_QUEUE}
      TASK_TABLE: '${env:TASK_EXEC_TASK_TABLE}-${self:provider.stage}'
    events:
      - sqs:
          arn: "arn:${self:custom.cloud}:sqs:${self:provider.region}:${self:custom.accountid}:${self:custom.updateTaskQueue}"

