service: task-list-service
frameworkVersion: ">=1.30.0"
plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-dotenv-plugin
custom:
  accountid: ${env:AWS_ACCOUNT_ID}
  cloud: ${env:TARGET_CLOUD}
  region: ${env:TARGET_REGION}
  domain: ${env:TASK_LIST_DOMAIN}
#  userPoolArn: ${env:TASK_LIST_USER_POOL_ARN}
  dotenv:
    path: ../.env
  customDomain:
    domainName: 'tasklistapi.${self:custom.domain}'
    stage: ${self:provider.stage}
    basePath: v1
    certificateName: '*.${self:custom.domain}'
    createRoute53Record: true
    endpointType: regional
  serverless-offline:
    port: 3000

provider:
  name: aws
  region: ${env:TARGET_REGION}
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  endpointType: regional
  environment:
    TASK_TABLE: '${env:TASK_EXEC_TASK_TABLE}-${self:provider.stage}'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:${self:custom.cloud}:dynamodb:${self:custom.region}:${self:custom.accountid}:*"

functions:
  create:
    handler: handler.create
    role: arn:${self:custom.cloud}:iam::${self:custom.accountid}:role/task-list
    events:
      - http:
          method: POST
          path: tasks
          cors: true
#          authorizer:
#            arn: '${self:custom.userPoolArn}'
  read:
    handler: handler.read
    role: arn:${self:custom.cloud}:iam::${self:custom.accountid}:role/task-list
    events:
      - http:
          method: GET
          path: tasks/{id}
          cors: true
#          authorizer:
#            arn: '${self:custom.userPoolArn}'
  update:
    handler: handler.update
    role: arn:${self:custom.cloud}:iam::${self:custom.accountid}:role/task-list
    events:
      - http:
          method: PUT
          path: tasks/{id}
          cors: true
#          authorizer:
#            arn: '${self:custom.userPoolArn}'
  delete:
    handler: handler.del
    role: arn:${self:custom.cloud}:iam::${self:custom.accountid}:role/task-list
    events:
      - http:
          method: DELETE
          path: tasks/{id}
          cors: true
#          authorizer:
#            arn: '${self:custom.userPoolArn}'
  list:
    handler: handler.list
    role: arn:${self:custom.cloud}:iam::${self:custom.accountid}:role/task-list
    events:
      - http:
          method: GET
          path: tasks
          cors: true
#          authorizer:
#            arn: '${self:custom.userPoolArn}'

